### ISSUE TITLE
The term "dedicated_master_type" is misleading

### ISSUE THREAD

**Issue by actionjack** [terraform-community-modules/tf_aws_elasticsearch#34]
The term "dedicated_master_type" is a little misleading in the documentation it seems to suggest that it is either a string for the machine type or a boolean. Which is it supposed to be?

**Comment by lipingtababa** [comment]
I think the terms are defined by AWS team rather than terraform team.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-elasticsearchclusterconfig.html
If you put these 3 configurations together, then they are obvious.

  "DedicatedMasterEnabled" : Boolean,
  "DedicatedMasterType" : String,
 "DedicatedMasterCount" : Integer,

**Comment by antonbabenko** [comment]
This has been fixed in [v1.2.0](https://github.com/terraform-community-modules/tf_aws_elasticsearch/releases/v1.2.0) where `dedicated_master_type` is now a string.
